import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MenuBar from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          display: "flex",
          justifyContent: "space-between",
        }}
      >
        <ToastContainer />
        <MenuBar />
        <div
          style={{
            width: "calc(100% - 200px)",
            height: "calc(100vh - 6rem)",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
